#!/usr/bin/env php
<?php
defined('YII_DEBUG') or define('YII_DEBUG', false);
defined('YII_ENV') or define('YII_ENV', 'prod');

require(__DIR__ . '/vendor/autoload.php');

$portalium = new \portalium\Portalium();
$portalium->setBaseYiiFile(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');
$portalium->setConfigFiles([
    __DIR__ . '/common/config/main.php',
    __DIR__ . '/common/config/main-local.php',
    __DIR__ . '/console/config/main.php',
    __DIR__ . '/console/config/main-local.php'
]);
$portalium->run();
